#### NumPy

<h6> NumPy arrays are stored more efficiently than Python lists and allow mathematical operations to be vectorized.</h6>

<h6> Vectorized operations have significantly higher performance compared to looping constructs in Python. </h6>

<h6> Benefits of NumPy arrays: </h6>
* Continguous allocation in memory <br>
* Vectorized <br>
* Boolean selection <br>
* Sliceability

In [3]:
import numpy as np

###### Creating NumPy arrays from a list

In [5]:
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [10]:
type(a1)

numpy.ndarray

In [7]:
a1.dtype

dtype('int32')

In [8]:
np.size(a1)

5

In [13]:
ls2 = [0]*10
ls2

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [14]:
a2 = np.array(ls2)
a2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
r3 = range(10)
r3

range(0, 10)

In [18]:
type(r3)

range

In [17]:
a3 = np.array(r3)
a3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### Creating NumPy arrays more efficiently

In [19]:
a3a = np.zeros(10)
a3a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
a3b = np.zeros(10, dtype=int)
a3b             

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
a4 = np.arange(0, 10, dtype=float)
a4

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [23]:
a5 = np.arange(0, 10, 2)
a5

array([0, 2, 4, 6, 8])

In [25]:
a6 = np.arange(10, 0, -1)
a6

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [29]:
a7 = np.linspace(0, 10, 21)
a7

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [38]:
# multiply an NumPy array by a number
print(f"a7 is an {type(a7)} NumPy array --> {a7} \n")
print(f"a7 * 10 --> {a7*10}")

a7 is an <class 'numpy.ndarray'> NumPy array --> [ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ] 

a7 * 10 --> [  0.   5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.
  70.  75.  80.  85.  90.  95. 100.]


In [41]:
a8 = np.arange(1, 10, 2)
a9 = np.arange(11, 20, 2)
a10 = a8 + a9                               # arrays have to be the same size and dimension for operations across two or more arrays
a10

array([12, 16, 20, 24, 28])

In [43]:
a11 = np.array([[11, 12], [21, 22]])
a11

array([[11, 12],
       [21, 22]])

In [44]:
a12 = np.array([np.arange(11, 13), np.arange(21, 23)])
a12

array([[11, 12],
       [21, 22]])

In [51]:
a13 = np.arange(1, 101)
a13 = a13.reshape(20, 5)
a13

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [53]:
a14 = np.arange(1, 101).reshape(20, 5)
a14

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

In [54]:
np.size(a14)

100

In [55]:
np.size(a14, 0)      # 0 refers to rows

20

In [58]:
np.size(a14, 1)      # 1 refers to columns

5

In [66]:
a14[9]            # selects the 10th row of a two-dimensional array (using zero-position indexing)

array([46, 47, 48, 49, 50])

In [67]:
a14[3, 2]         # picks off the 4th row, 3rd column value (using zero-position indexing)

18

In [68]:
a14[9, ]          # identical to a14[9]

array([46, 47, 48, 49, 50])

In [69]:
a14[:, 0]         # selects the 1st column of a two-dimensional array

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [75]:
a15 = np.arange(10, 15)
a15

array([10, 11, 12, 13, 14])

In [65]:
a15[2]

12

In [70]:
a16 = np.arange(0, 27).reshape(3, 3, 3)
a16

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
a16[1, 1, 2]

14

In [76]:
a15 <= 12

array([ True,  True,  True, False, False])

In [78]:
(a15 <= 11) | (a15 >= 13)

array([ True,  True, False,  True,  True])

In [82]:
def timesN(x, N):
    return x*N

np.vectorize(timesN)(a15, 5)

array([50, 55, 60, 65, 70])